name: Generate OSS Badge
on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly (Sundays at midnight)

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: mabd-dev/gh-oss-stats@dev
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.repository_owner }}
          badge-style: summary
          badge-theme: dark
          badge-output: images/oss-badge.svg
          version: latest
